AWSTemplateFormatVersion: '2010-09-09'
Description: This will create the dynamodb tables,lambda functions for the bus services.
Parameters:
  ResourceBucket:
    Type: String
  LambdaCodeKey:
    Type: String
    Description: S3 key of the Lambda deployment package
  NodeLayerARN:
    Type: String
    Description: ARN of the node module layer
  AppConsoleUrl:
    Type: String
    Description: Console url
Outputs:
  VehicleStateLogsARN:
    Description: ARN of vehicle state logs table.
    Value: !GetAtt VehicleStateLogs.Arn
  BusesARN:
    Description: ARN of registered buses table.
    Value: !GetAtt Buses.Arn
  WebSocketConnBusesARN:
    Description: ARN of bus's websocket connection table.
    Value: !GetAtt WebSocketConnBuses.Arn
  WebSocketConnPassengersARN:
    Description: ARN of passengers's websocket connection table.
    Value: !GetAtt WebSocketConnPassengers.Arn
Resources:
  Buses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Buses
      AttributeDefinitions:
        - AttributeName: bus_no
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: bus_no
          KeyType: HASH
  VehicleStateLogs:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VehicleStateLogs
      AttributeDefinitions:
        - AttributeName: bus_no
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: bus_no
          KeyType: HASH
  WebSocketConnBuses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WebSocketConnBuses
      AttributeDefinitions:
        - AttributeName: connection_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: connection_id
          KeyType: HASH
  WebSocketConnPassengers:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WebSocketConnPassengers
      AttributeDefinitions:
        - AttributeName: connection_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: connection_id
          KeyType: HASH
  BusLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BusLambdaExecutionRole
      Description: This role give permissions for lambda to execute certain action on dynamodb.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamodbAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: DynamodbAccess
                Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:BatchGetItem
                  - dynamodb:ConditionCheckItem
                  - dynamodb:DescribeTable
                  - dynamodb:GetRecords
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:BatchWriteItem
                  - dynamodb:DeleteItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                Resource:
                  - !GetAtt Buses.Arn
  BusLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: BusLambda
      Description: This lambda will invoke defined in lib/lambda/bus.js.
      Code:
        S3Bucket: !Ref ResourceBucket
        S3Key: !Ref LambdaCodeKey
      MemorySize: 1024
      Handler: lib/lambda/api/bus.handler
      Timeout: 60
      Runtime: nodejs22.x
      Role: !GetAtt BusLambdaExecutionRole.Arn
      Layers:
        - !Ref NodeLayerARN
      Environment:
        Variables:
          AWS_ACCOUNT_ID: !Ref AWS::AccountId
          APP_CONSOLE_URL: !Ref AppConsoleUrl