AWSTemplateFormatVersion: '2010-09-09'
Description: This template will create cognito User pool, User groups, Related lambda function and IAM roles.
Parameters:
  ResourceBucket:
    Type: String
  LambdaCodeKey:
    Type: String
    Description: S3 key of the Lambda deployment package
Outputs:
  UserPoolId:
    Description: User pool ID
    Value: !Ref UserPool
  UserPoolClientID:
    Description: User pool client ID
    Value: !Ref UserPoolClient
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      MfaConfiguration: 'OFF'
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          PasswordHistorySize: 5
          RequireLowercase: 'true'
          RequireNumbers: 'true'
          RequireSymbols: 'true'
          RequireUppercase: 'true'
          TemporaryPasswordValidityDays: 7
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: 'false'
          Mutable: 'true'
          Name: email
          Required: 'true'
        - AttributeDataType: String
          DeveloperOnlyAttribute: 'false'
          Mutable: 'true'
          Name: role
          Required: 'true'
      UserPoolAddOns:
        AdvancedSecurityMode: 'OFF'
      UserPoolName: MobileApp
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: UserPoolClient
      AccessTokenValidity: 30
      AuthSessionValidity: 5
      IdTokenValidity: 5
      RefreshTokenValidity: 5
      TokenValidityUnits:
        AccessToken: 'days'
        IdToken: 'days'
        RefreshToken: 'days'
      UserPoolId: !Ref UserPool
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: 'false'
      PreventUserExistenceErrors: LEGACY
      ReadAttributes:
        - email
        - 'custom:role'
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This group for handling the admin users
      GroupName: AdminGroup
      Precedence: 1
      UserPoolId: !Ref UserPool
  BusGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This group for handling the Bus owners
      GroupName: BusGroup
      Precedence: 2
      UserPoolId: !Ref UserPool
  PassengerGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This group for handling the passengers
      GroupName: PassengerGroup
      Precedence: 3
      UserPoolId: !Ref UserPool
  DisabledGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      Description: This group for handling the disabled users
      GroupName: DisabledGroup
      Precedence: 4
      UserPoolId: !Ref UserPool
  AuthLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AuthLambdaExecutionRole
      Description: This role give permissions for lambda to execute certain action on cognito.
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        PolicyName: CognitoAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Sid: CognitoAccess
              Effect: Allow
              Action:
                - cognito-idp:SignUp
                - cognito-idp:ConfirmSignUp
                - cognito-idp:ResendConfirmationCode
                - cognito-idp:InitiateAuth
                - cognito-idp:RespondToAuthChallenge
                - cognito-idp:ForgotPassword
                - cognito-idp:ConfirmForgotPassword
                - cognito-idp:ChangePassword
                - cognito-idp:AdminAddUserToGroup
                - cognito-idp:AdminGetUser
              Resource:
                - !Sub
                    - arn:aws:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${PoolId}
                    - PoolId: !Ref UserPool

